name: 公开ollama查询

on:
  schedule:
    # 定时任务 每天午夜12点执行一次, UTC时间 +8小时为北京时间
    - cron: '0 16 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

env:
  #  设置时区，jobs 获取为北京时间
  TZ: Asia/Shanghai

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'

      - run: npm i
      - run: node index.js

      - name: 获取当前时间
        id: time
        shell: bash
        run: echo "time=$(date +'%Y-%m-%d %H:%M:%S')" >> ${GITHUB_OUTPUT}

      - name: ip文件
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build # 提交到那个分支
          commit-message: 发布于：${{ steps.time.outputs.time }} # 提交信息
          folder: build
